### ISSUE TITLE
How to use this in Ros Melodic？

### ISSUE THREAD

**Issue by feelinggxj** [Ar-Ray-code/YOLOX-ROS#1]
Hi！Thanks for your awsome contribution.
if i want to compile and use this code in ubuntu 18.04&Ros Melodic，should i change something？
hoping your reply！
こんにちは！あなたの素晴らしい貢献に感謝します。
このコードをubuntu18.04Ros Melodicでコンパイルして使用したい場合、何かを変更する必要がありますか？
お返事をお待ちしております！

**Comment by Ar-Ray-code** [comment]
Thank you for your comment.
I only have Ubuntu 20, but I ported it to ROS1. In my experience, Noetic and Melodic are compatible.

There are probably still some bugs, but please feel free to make additional comments when you do.

https://github.com/Ar-Ray-code/YOLOX-ROS/tree/noetic

**Comment by feelinggxj** [comment]
Thanks a lot! I try this branch soon and then update the issue.
    Best wishes！

**Comment by Ar-Ray-code** [comment]
If you have any other problems, please make a new issue.

**Comment by qiao19881314** [comment]
> ```
> Thanks a lot! I try this branch soon and then update the issue.
> Best wishes！
> ```
Hi feelingXj， have you  try  it  on Melodic？
