### ISSUE TITLE
Can this project support ros1

### ISSUE THREAD

**Issue by nuo-1** [Ar-Ray-code/YOLOX-ROS#10]
I want use yolox-ros in melodic. can this project run in ROS1?

**Comment by Ar-Ray-code** [comment]
I think your comment is similar to #1 .
Try on Python3 + ROS Melodic.
Note that YOLOX does not support Python2.

**Comment by Ar-Ray-code** [comment]
I will not support ROS1 + YOLOX, so you have to create your own. Your pull requests are welcome. :+1:

**Comment by nuo-1** [comment]
> I think your comment is similar to #1 . Try on Python3 + ROS Melodic. Note that YOLOX does not support Python2.

Thanks ! I try this branch soon and then update the issue.
Best wishes！
