### ISSUE TITLE
Run in melodic

### ISSUE THREAD

**Issue by hongSS0919** [Ar-Ray-code/YOLOX-ROS#12]
Sorry, I want to ask how this project works on melodic. I reported an error directly to catkin make. Before catkin make, I executed the following two commands to use Python 3
catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so

catkin config --instal
![Screenshot from 2022-03-08 19-35-00](https://user-images.githubusercontent.com/76800494/157230740-0c5a6c43-f308-4e43-9b16-e94503ed29a2.png)
l

**Comment by Ar-Ray-code** [comment]
I don't understand about that log `ament_python`...

Did you run `git checkout noetic` ?

**Comment by hongSS0919** [comment]
I'm sorry, I don't seem to understand what you mean. I'll write down my operation flow:
1.mkdir -p yoloxx_ws/src && cd yoloxx_ws
2.catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
3.catkin config --install
4.cd src && git clone https://github.com/Ar-Ray-code/YOLOX-ROS.git
5.cd ..
6.catkin_ make
I don't know if there is something wrong with my operation. My ros version is melodic
![Screenshot from 2022-03-09 09-38-50](https://user-images.githubusercontent.com/76800494/157355884-ba58f8c5-ead6-4dc5-b33e-c0feea48ec2f.png)

**Comment by hongSS0919** [comment]
ament_pyhton looks like something in ros2

**Comment by Ar-Ray-code** [comment]
Please try following.
 
```bash
sudo apt install ros-melodic-usb-cam
source <your-ros-env-directory>/setup.bash
mkdir -p ~/ros1_ws/src
cd ~/ros1_ws
catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
catkin config --install

cd ~/ros1_ws/src
catkin_init_workspace
git clone git@github.com:Ar-Ray-code/YOLOX-ROS.git -b noetic --recursive # <- checkout and clone submodule
cd ~/ros1_ws
catkin_make
```

If you can't use `git@github.com:`, please try to use `https://github.com/` to download and clone [bbox_ex_msgs](https://github.com/Ar-Ray-code/bbox_ex_msgs/tree/ros1) manually.

**Comment by hongSS0919** [comment]
Thank you very much for your timely reply.  Do I need to put YOLOX into YOLOX_ROS ? Which directory should I put it in
![Screenshot from 2022-03-09 11-15-23](https://user-images.githubusercontent.com/76800494/157366169-4e2bb6b7-ddc5-42d9-971e-9e1472a48dbe.png)
？

**Comment by Ar-Ray-code** [comment]
YOLOX-ROS does not contain YOLOX.
Read README.

**Comment by hongSS0919** [comment]
I'm sorry to bother you again. I still have this situation: ModuleNotFoundError: No module named 'yolox'.  I have read README, but I haven't found any solution 
![Screenshot from 2022-03-09 14-20-58](https://user-images.githubusercontent.com/76800494/157384237-6e056426-480d-445c-9853-b3584926e7b0.png)

**Comment by hongSS0919** [comment]
I'm really sorry to bother you again.  I feel that there are still problems in my operation . Instead of using a web camera, I wrote a cpp file myself, read the photos in the folder repeatedly, and publish them as topics, but I didn't find the results.

**Comment by hongSS0919** [comment]
![Screenshot from 2022-03-09 14-38-44](https://user-images.githubusercontent.com/76800494/157387227-b8bb3f1f-acb5-4856-aa04-0dcb2b3299f3.png)

**Comment by hongSS0919** [comment]
![Screenshot from 2022-03-09 14-47-45](https://user-images.githubusercontent.com/76800494/157387522-3b693fa0-0222-4d47-a893-fb628296de57.png)
![Screenshot from 2022-03-09 14-47-46](https://user-images.githubusercontent.com/76800494/157387526-9a77c9ea-8c3a-4c7e-bdb0-87bc878ac888.png)

**Comment by Ar-Ray-code** [comment]
Well...
I have made something similar.

[Ar-Ray-code/movie_publisher/picture_publisher.cpp](https://github.com/Ar-Ray-code/movie_publisher/blob/noetic-devel/src/picture_publisher.cpp)
I don't know if it will work in your environment...

**Comment by hongSS0919** [comment]
Thank you very much. My publisher is similar to yours. I don't think my picture publisher exists problem, but the above problem still hasn't been solved. I read your source code. If it works normally, the  results of picture should appear automatically by opencv function : imshow().
![Screenshot from 2022-03-09 15-38-49](https://user-images.githubusercontent.com/76800494/157395091-7f7a3d41-4f65-4bbb-83c4-a50ee98bc764.png)

**Comment by hongSS0919** [comment]
How do you check the information in the bounding box? such as: 
![yolox_topic](https://user-images.githubusercontent.com/76800494/157396287-cc2f2bc2-4518-4dfe-a404-96cfc60f7bff.png)

**Comment by hongSS0919** [comment]
I think it hasn't executed the callback function, but I'm sure the picture has been published

**Comment by hongSS0919** [comment]
![Screenshot from 2022-03-09 16-02-23](https://user-images.githubusercontent.com/76800494/157398301-e6b7bccd-5079-4781-9dc7-63c1fcbf633d.png)
![Screenshot from 2022-03-09 16-02-46](https://user-images.githubusercontent.com/76800494/157398304-746a8cce-4889-41fd-bb07-0d4e24926621.png)

**Comment by Ar-Ray-code** [comment]
Umm...
Last update of YOLOX-ROS noetic branch is August 2021, so it may have version mismatch.
I think you have to use older YOLOX version (e.g. [v0.1.0](https://github.com/Megvii-BaseDetection/YOLOX/releases/tag/0.1.0) and legacy models.

**Comment by hongSS0919** [comment]
According to your suggestion, I used  YOLOX v0 1.0, but the problems are the same as what I described above. Execute exception when calling callback function.
