### ISSUE TITLE
Connect to gazebo camera

### ISSUE THREAD

**Issue by giorgiozannini** [Ar-Ray-code/YOLOX-ROS#14]
Good morning, first of all thanks for the amazing and interesting work! I was able to run the code on my webcam but I was wondering if it is possible to connect to the camera topics for SITL simulations like with Gazebo. Can you kindly point me in this direction if it is possible?
Thanks again for publishing this code and I wish you a good day.

**Comment by Ar-Ray-code** [comment]
added [yolox_nano_onnx_gazebo.launch.py](https://github.com/Ar-Ray-code/YOLOX-ROS/blob/main/yolox_ros_py/launch/yolox_nano_onnx_gazebo.launch.py)
