### ISSUE TITLE
Problems while sourcing

### ISSUE THREAD

**Issue by Marcel2103** [Ar-Ray-code/YOLOX-ROS#25]
It was not possible for me to follow the guide: 
source ~/arams_ws/install/local_setup.bash

This command leads to the error: 
not found: "/home/marcel/arams_ws/install/yolox_cpp/share/yolox_cpp/local_setup.bash"
not found: "/home/marcel/arams_ws/install/yolox_ros_cpp/share/yolox_ros_cpp/local_setup.bash"

I'm sorry but with my limited ROS2 knowledge I don't know where to search for a solution for this problem.

**Comment by Ar-Ray-code** [comment]
This message means that neither TensorRT nor OpenVINO is on your computer.

yolox_cpp will exclude from the building list if neither is loaded, and yolox_ros_cpp will exclude it if yolox_cpp is not built.

---

If you want to use yolox_ros_py's (using onnxruntime) it does not matter for execution.

**Comment by Ar-Ray-code** [comment]
Consider the implications of publishing under the Apach License 2.0.
Your coding makes all your requests possible.
