### ISSUE TITLE
Edit YOLOX pth/exp values without changing launch file

### ISSUE THREAD

**Issue by JonathanNash21** [Ar-Ray-code/YOLOX-ROS#27]
Hello,

Is it possible to specify parameters in the launch file (like those in the title) via command line arguments? Or do I have to go into the launch.py and manually edit the launch_ros.actions.Node parameters? Thank you.

**Comment by JonathanNash21** [comment]
And along the same idea, is there a simple way to add a namespace (like https://iroboteducation.github.io/create3_docs/setup/multi-robot/ uses) to the bounding_boxes publisher for subscribing to? Or will I have to manually edit that as well?

**Comment by Ar-Ray-code** [comment]
You can launch yolox-ros-cpp with arguments, but yolox-ros-py can't now.
[yolox_openvino.launch.py](https://github.com/Ar-Ray-code/YOLOX-ROS/blob/main/yolox_ros_cpp/yolox_ros_cpp/launch/yolox_openvino.launch.py)

```bash
ros2 launch yolox_ros_cpp yolox_openvino.launch.py video_device:=/dev/video0
```

**Comment by Ar-Ray-code** [comment]
If you want to set namespace on launch file, add `namespace` parameter in `launch_ros.actions.Node`.

[Example (motpy-ros)](https://github.com/Ar-Ray-code/motpy_ros/blob/main/motpy_ros/launch/example_darknet.launch.py#L11)

**Comment by JonathanNash21** [comment]
I appreciate the quick response! Thank you!
