### ISSUE TITLE
Green Screen when launching yolox_ros_py

### ISSUE THREAD

**Issue by JonathanNash21** [Ar-Ray-code/YOLOX-ROS#28]
Hello,

When I run yolox_ros_py on my Jetson Nano, I encounter a green screen like in the screenshot. This happens when using yolox_nano_torch for both the cpu and gpu versions - the Docker container I'm using only has PyTorch, so I can't run the other options. I've checked running a GStreamer application, and that works both in the native environment and in the Docker container I'm running yolox_ros in - I think the issue might be with v4l2 or CvBridge, but I'm not entirely sure. Is there an easy way to apply GStreamer instead?
![PXL_20221026_012229838](https://user-images.githubusercontent.com/54086827/198314463-81b9754a-6dea-49fa-86de-ed55fea40122.jpg)
I've tried using the Dockerfile for Jetson Nano found in the yolox_ros_cpp folder, but the build fails at the 19th and 21st build commands (installing the onnxoptimizer from git and installing YOLOX from git) - if you have this image hosted on Dockerhub, I should be able to test and see if that will work by just downloading the built image.

**Comment by JonathanNash21** [comment]
I will add that I edited the dockerfile to be pull from dustynv/ros:galactic-ros-base-l4t-r32.7.1, I wouldn't think this would cause issues with building though

**Comment by Ar-Ray-code** [comment]
> I think the issue might be with v4l2 or CvBridge, but I'm not entirely sure. Is there an easy way to apply GStreamer instead?

If you think v4l2-camera is the cause, then I don't think this issue comes from Jetpack. rqt_graph should see if it shows the screen.

Checking that the [YOLOX](https://github.com/Megvii-BaseDetection/YOLOX) demo.py works correctly in the container would be a good way to get some hints. Please give it a try.

**Comment by JonathanNash21** [comment]
Sorry, I should've gotten back to this earlier - I fixed the issue by changing the pipeline to use GStreamer through a combination of using https://github.com/BrettRD/ros-gst-bridge instead of v4l2-camera as the webcam node in the launch file (not sure if this does anything important due to the next thing) and then using a gstreamer pipeline via OpenCV to open the camera in yolox_ros.py, which I convert to a ROS message via the CvBridge to be able to publish the video frames.
