### ISSUE TITLE
Some trouble in running

### ISSUE THREAD

**Issue by geekfuns** [Ar-Ray-code/YOLOX-ROS#3]
Hi,when i running the program , i got some trouble

Could not import "pyqt" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    from . import libqt_gui_cpp_sip
ImportError: dynamic module does not define module export function (PyInit_libqt_gui_cpp_sip)

libgcc_s.so.1 must be installed for pthread_cancel to work

i had already installed the pyqt , how can i solve it ?
Thanks!

**Comment by Ar-Ray-code** [comment]
I don't use ROS-Melodic on Ubuntu18 and I cannot try test.

Please tell me more informations. Maybe I can tell you something.

YOLOX-ROS is tested on ROS-Foxy and ROS-Noetic on Ubuntu20. If you want running this on ROS-Melodic, please check the following points.

1. What is the Python runtime? Python 2.7 is not supported. Please use Python3. If you don't know how to use Python3 , please check this [link](https://answers.ros.org/question/348093/using-ros-melodic-with-python-3/).
2. PyQt is not using this project (YOLOX-ROS). Therefore, the error does not originate from YOLOX-ROS.

**Comment by geekfuns** [comment]
Thanks ! May it caused by the ROS version , I wiil try it on Noetic.

Ar-Ray ***@***.***> 于2021年10月5日周二 下午4:34写道：
