### ISSUE TITLE
How to change the topic?

### ISSUE THREAD

**Issue by Nobody-Zhang** [Ar-Ray-code/YOLOX-ROS#35]
Hello~ I'm a student trying to use this YOLOX-ROS (batch : ros1) in a program. But the robot publish Image from 'drone_0/Scene', so how can i change the code to adapt this fantastic source to the robot?
thx a lot

**Comment by Ar-Ray-code** [comment]
ROS1? I cannot guarantee that it will work because of the planned EOL for ROS1...

Please read the following document for more information on ROS1 remapping.

- [Remapping Arguments](http://wiki.ros.org/Remapping%20Arguments)
- [roslaunch/XML/remap](http://wiki.ros.org/roslaunch/XML/remap)

**Comment by Nobody-Zhang** [comment]
Thank U for answering my question.
I've read the document U gived.

ummmm, I've deleted something in launch file and py.

Like this:
Line 110:
![image](https://user-images.githubusercontent.com/45116315/216029230-349b9815-dff5-4cce-a079-9d298a1888be.png)

Deleated something:
![image](https://user-images.githubusercontent.com/45116315/216029396-190bf173-f60a-4b20-9c2e-dbcae7923db1.png)

The result is: ...
![image](https://user-images.githubusercontent.com/45116315/216029099-19ecb2ab-b7e8-49bf-b37d-9f8a682d087f.png)

QWQ could U please

**Comment by Nobody-Zhang** [comment]
> ROS1? I cannot guarantee that it will work because of the planned EOL for ROS1...
> 
> Please read the following document for more information on ROS1 remapping.
> 
> * [Remapping Arguments](http://wiki.ros.org/Remapping%20Arguments)
> * [roslaunch/XML/remap](http://wiki.ros.org/roslaunch/XML/remap)

![image](https://user-images.githubusercontent.com/45116315/216047957-d385c3df-925b-4b35-8f88-15ccaa2b8402.png)


Hey, thanks 2 U, I almost succeed in finishing this!
But。。。Qt version of Ur computer is?

**Comment by Nobody-Zhang** [comment]
Rewrite a python script.
Problem fixed.
