### ISSUE TITLE
tensorrt convert.bash error 

### ISSUE THREAD

**Issue by porizou** [Ar-Ray-code/YOLOX-ROS#42]
以下の手順で
YOLOX-ROS/yolox_ros_cpp/docker/tensorrt/　にあるDockerfileを使って
docker コンテナを作成、実行し、'tensorrt/convert.bash' を実行するとエラーが出ました。

```bash
cd ~/ros2_ws/src
git clone --recursive https://github.com/Ar-Ray-code/YOLOX-ROS -b humble

cd YOLOX-ROS/yolox_ros_cpp/docker/tensorrt/

docker build \
    --build-arg TENSORRT_VERSION=8.6 \
    --build-arg CUDNN_VERSION=8.8 \
    --build-arg PYTHON_VERSION=3.10 \
    -t yolox_tensorrt_image .

docker run \
    --name yolox_tensorrt \
    --network host \
    --runtime nvidia \
    -e DISPLAY=$DISPLAY \
    -v $HOME/ros2_ws:/root/ros2_ws \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    --device /dev/video0:/dev/video0 \
    -w /root/ros2_ws \
    -it \
    yolox_tensorrt_image bash
```

```bash
~/ros2_ws# ./src/YOLOX-ROS/weights/tensorrt/convert.bash yolox_tiny 16
Model Name: yolox_tiny
Workspace size: 16

./src/YOLOX-ROS/weights/tensorrt/convert.bash: line 35: /usr/src/tensorrt/bin/trtexec: No such file or directory
```

**Comment by Ar-Ray-code** [comment]
issue投稿ありがとうございます。
結論から先に申し上げますと、動かない原因は、そのDockerfileがonnxruntime向けのビルドでTensorRTをサポートしていないためです。

引数やドキュメントの不備が混乱を招いてしまい申し訳ありません。

今すぐ試したい場合はネイティブ環境でTensorRTを構築してビルドすることをお勧めします。

<br>

一方で引数に提示されている通り、ちょうど数週間前にTensorRT8.6がリリースされたそうで、こちらはUbuntu22.04+CUDA12環境でも動きそうなのでそちらをベースにDockerfileを構築できるような環境を整える予定です。

今暫くお待ちください。PRも歓迎いたします。

参照：https://forums.developer.nvidia.com/t/cuda-toolkit-12-0-0-tensorrt-sdk-is-needed/237364/3

**Comment by Ar-Ray-code** [comment]
I have confirmed that it works with v0.4.1.
Please open a new issue if this problem persists.
