### ISSUE TITLE
The class_id of bboxes_ex_msgs::msg::BoundingBoxes that is pubbed does not change when I have it inferred with custom data.

### ISSUE THREAD

**Issue by ryosei1250** [Ar-Ray-code/YOLOX-ROS#46]
I use translation software

When inferring custom data, I added the newly created txt file to class_labels_path in yolox_tensorrt.launch.py, but the class_id to be pubbed is still existing. Do you know of a solution?
![Screenshot from 2024-02-01 16-00-04](https://github.com/Ar-Ray-code/YOLOX-ROS/assets/85102489/69ee4c1b-886a-458a-8f72-2adb3e2819ed)
![Screenshot from 2024-02-01 15-59-31](https://github.com/Ar-Ray-code/YOLOX-ROS/assets/85102489/09a1ab33-c3ef-486c-be35-2076cbc6767a)
![Screenshot from 2024-02-01 15-58-34](https://github.com/Ar-Ray-code/YOLOX-ROS/assets/85102489/d9f24225-ab32-4829-84e9-ca520d02a35d)
![Screenshot from 2024-02-01 15-57-47](https://github.com/Ar-Ray-code/YOLOX-ROS/assets/85102489/a9730023-42ae-44e5-812a-076db462cd85)

**Comment by ryosei1250** [comment]
Sorry, it solved itself.
Sorry for submitting the issue without looking at the code carefully.
I added a new .hpp file so that yolox_cpp::COCO_CLASSES is defined in coco_names.hpp and it worked.
Is this approach correct?

**Comment by Ar-Ray-code** [comment]
You are right and I apologize for my lack of maintenance.
On the other hand, the essence of yolox is not the retrieval of class_id (e.g id='person') but the id (e.g id=0), and that information is not included in the input onnx or trt. Therefore, it is only a drawing utility and the boundingbox subscriber should use id.
We are currently experimenting with a revised interface using pluginlib, so please wait a little longer for the fix! 🙂

(ref1 : https://github.com/StrayedCats/detector2d)
(ref2 : https://github.com/StrayedCats/yolox_trt)

**Comment by ryosei1250** [comment]
Thanks for the reply.
Thank you for making yolox available for ros2, Ar-Ray-code's blog is very informative.
Thank you for sharing the essence of yolox.
