### ISSUE TITLE
No module named 'bboxes_ex_msgs'

### ISSUE THREAD

**Issue by guo1104b** [Ar-Ray-code/YOLOX-ROS#9]
Hi, I try to run the demo of python version and want to check the result by typing "ros2 topic echo /yolox/bounding_boxes", but it shows "No module named 'bboxes_ex_msgs". I don't know why, please have a look , thank you very much!
<img width="815" alt="1" src="https://user-images.githubusercontent.com/50586572/145651544-b4230191-b4e9-4efd-bb84-ee0739845d3f.PNG">

**Comment by Ar-Ray-code** [comment]
`bbox_ex_msgs` is submodule.

Please try these commands.

```bash
cd YOLOX-ROS
git submodule update --init
```

**Comment by Ar-Ray-code** [comment]
If you have additional comments, please open this issue again.
